### ISSUE TITLE
PlatformIO cannot find PDM.h

### ISSUE THREAD

**Issue by fantasyEthan** [RAKWireless/RAKwireless-Audio-library#6]
Hardware: RAK11200+RAK18032
Software: VSCode, PlatformIO
PC: Macbook Pro 2021 (14inch) M1

My platformio.ini
<img width="883" alt="image" src="https://user-images.githubusercontent.com/54493995/209673818-86f210dc-3e9c-43d9-afb1-6f8535b33956.png">

Build Image
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/54493995/209673911-3dac10e2-0dc7-4ba4-8c9c-923c694f3cde.png">
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/54493995/209673973-3cff3852-542d-4747-a5b4-e212dc00fff9.png">

I can run correctly in Arduino, but failed to build in PlatformIO

**Comment by beegee-tokyo** [comment]
The RAKwireless Audio Library depends on patches that are done in the RAKwireless BSP for Arduino. In PlatformIO you are using the original Espressif BSP which doesn't have these patches.

**Comment by fantasyEthan** [comment]
So I can only use Arduino instead of PlatformIO for my use right?

**Comment by beegee-tokyo** [comment]
At the moment yes, our team is looking into PIO now, but I cannot say if we can publish our own PIO BSP soon.
